.\"
.\"	aohkd.1		 	ALE one-hand keyboard daemon man page
.\"
.\"	Copyright (c) 2009 by Johns.  All Rights Reserved.
.\"
.\"	Contributor(s):
.\"
.\"	License: GPLv2
.\"
.\"	This file is part of ALE one-hand keyboard
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; only version 2 of the License.
.\"
.\"	$Id$
.\" ------------------------------------------------------------------------
.pc
.TH "aohkd" 1 "2009-05-27" "0.06" "ALE one-hand keyboard daemon Manual"

.SH NAME
aohkd \- is an userland driver for the ALE one-hand keyboard.

.SH SYNOPSIS
.B aohkd
.I [-?|-h]
.I [-b]
.I [-L]
.I [-D]
.I [-d dev]
.I [-v id]
.I [-p id]
.I [-n]
.I [-l lang]
.I [-s file]
.I [mappings]

.SH DESCRIPTION
aohkd is an user space driver for the ALE one-hand keyboard.

The ALE one-hand keyboard is a design study.  There is no plug&play hardware
available yet.  It is currently a software only solution.

You can type with only one hand (just one finger is possible) using a standard
keyboard.  Only the number pad is used, the remaining keyboard is still full
functional.

It is a no chording solutions.  Instead of pressing "a", you should type "42",
press and release "4" than press and release the "2".  Which should gives you
the half speed of normal typing.  But you don't have to move the hand, so
higher speed is possible.  You can save the travel time and you can use the
mouse with one hand and the keyboard with the other.

PS/2 and USB keyboards and keypads are supported.  Also special input devices
like tactical commander, zboard, nostromo speedpad, Pro Gamer Command Pad,
ErgoMedia 500 should work.

Useful for the disabled user, professionals and gamers.

.SH OPTIONS
.TP
.B -?|-h
Show help options.
.TP
.B -b
Background.  aohkd run in the background as daemon.  Errors will be logged
to syslog.
.TP
.B FIXME:
Need to complete the man pages

.SH AUTHOR

.SH AUTHOR
Lutz "Johns" Sammer (2000-9) <johns98@gmx.net>.

.SH SEE ALSO
aohk.map(5) for the input/output keyboard mapping.

.SH COPYRIGHT
Copyright (C) 2009 Johns.  License: GPLv2
