.\"
.\"	utv.1		 	µtv man page
.\"
.\"	Copyright (c) 2009 by Johns.  All Rights Reserved.
.\"
.\"	Contributor(s):
.\"
.\"	License: AGPLv3
.\"
.\"	This program is free software: you can redistribute it and/or modify
.\"	it under the terms of the GNU Affero General Public License as
.\"	published by the Free Software Foundation, either version 3 of the
.\"	License.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU Affero General Public License for more details.
.\"
.\"	$Id: $
.\" ------------------------------------------------------------------------
.pc
.TH "µTV" 1 "2009-02-11" "0.01" "µTV Manual"

.SH NAME
µtv \- a lightweight and efficient digital television (DVB) viewer for x11

.SH SYNOPSIS
.B µtv
.I [-?|-h]
.I [-c]
.I [-v]
.I [-t]

.SH DESCRIPTION
µTV is a x11 desktop application for watching digital television services
that use the DVB standard.  µTV works with DVB-S/DVB-S2 and DVB-T cards that
have kernel driver support.

µtv uses ffmpeg as codec library and SDL as output library.

.SH OPTIONS
.TP
.B -?|-h
Show help options.
.TP

.SH AUTHOR
Johns (2008-2009) <johns98@gmx.net>.

.SH COPYRIGHT
Copyright (C) 2008-2009 Johns.  License: AGPLv3
